spring:
  application:
    name: lv2-final-mission
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

holiday:
  service-key: dLpMvhdh/a6SmnIhCrNFqY/M4DDk7Jod5V69/K2YrIjQAy1XbcNW9fxulzegnEFI3Yoa1S0J/wK81KJrAA9Uyg==
  base-url: 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo'
