spring:
  application:
    name: lv2-final-mission
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:conference-room
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

holiday:
  service-key: dLpMvhdh/a6SmnIhCrNFqY/M4DDk7Jod5V69/K2YrIjQAy1XbcNW9fxulzegnEFI3Yoa1S0J/wK81KJrAA9Uyg==
  base-url: 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo'
