name: deploy-prod-server

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build Jar
        run: ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hula-jar
          path: build/libs/*SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: [self-hosted, prod]

    steps:
      # 1) 기존 JAR 백업
      - name: Backup existing artifact (if any)
        run: |
          mkdir -p ./artifacts/backup
          if ls ./artifacts/*.jar 1> /dev/null 2>&1; then
            for f in ./artifacts/*.jar; do
              cp "$f" ./artifacts/backup/
              echo "Backed up $f -> ./artifacts/backup/"
            done
            rm -f ./artifacts/*.jar
          else
            echo "No existing artifact to backup."
          fi

      # 2) 새 아티팩트 다운로드
      - name: Download Uploaded Artifact
        uses: actions/download-artifact@v4
        with:
          name: hula-jar
          path: ./artifacts

      - name: Kill Existing Server On Port 8080
        run: |
          PID=$(lsof -t -i :8080 || true)
          if [ -n "$PID" ]; then
            echo "Killing existing process: $PID"
            kill -9 $PID
          fi

      - name: Run App On Port 8080
        run: |
          JAR_FILE=$(ls -t ./artifacts/*.jar 2>/dev/null | head -n 1)
          echo "Starting server with $JAR_FILE"
          RUNNER_TRACKING_ID=""

          DATABASE_URL='${{ secrets.DATABASE_PROD_URL }}' \
          DATABASE_USERNAME='${{ secrets.DATABASE_PROD_USERNAME }}' \
          DATABASE_PASSWORD='${{ secrets.DATABASE_PROD_PASSWORD }}' \
          SPRING_PROFILES_ACTIVE=prod \
          nohup java -Duser.timezone=Asia/Seoul -jar "$JAR_FILE" --server.port=8080 > app.log 2>&1 &
